version: "3.7"

services:
  database:
    image: postgres
    container_name: database_budget
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=alura
      - POSTGRES_DB=budget
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: budget_api
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local